env:
  browser: true
  es2021: true
extends:
  - standard
  - eslint:recommended
  - prettier
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  new-cap: off
